# Generated by Django 2.0.5 on 2018-09-12 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='正文'),
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='标题', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='描述', max_length=100),
        ),
    ]
